select options_count value from one of the following 1) to 3) statements where complexity = {complexity}
 1) complexity == low, options_count = 2
 2) complexity == medium, options_count = 3.
 3) complexity == high, options_count = 5.
select total_options_count value from one of the following a) to c) statements where duration = {duration}
 a) duration == short, total_options_count =  5.
 b) duration == medium, total_options_count = 10.
 c) duration == large, total_options_count = 20.
The output of this prompt consist only in the correct answer(and no more text content) with this format:
options_count,total_options_count