The output of this prompt is the current  page  of the choose your own adventure novel story called {title}
The output of this prompt must be written in {language} language.
The characters for this story and it's synopsis is in {synopsis}.
The current page of {title} novel must continue  with the previous {option} choice from the previous prompt.
Each page has exactly {options} otpions to choose the next page based in a choice the reader has to take except the end page.
Each of the options must be preceded by it's number at the end of the page.